#!/bin/bash
echo '' > src/screens.js
cat doc/intro.md > doc/annotated-source.md
SOURCES=""
SOURCES+=" clock socket identity data turnover keyboard day-sched"
SOURCES+=" match-sched display-select league info-display"
SOURCES+=" managers/container managers/override managers/clock"
SOURCES+=" managers/kill-origin managers/day-sched managers/league"
SOURCES+=" managers/next-match managers/match-timing"
SOURCES+=" debug"
for SOURCE in $SOURCES
do
    echo "Compiling $SOURCE..."
    coffee --print src/coffee/$SOURCE.litcoffee >> src/screens.js
    cat src/coffee/$SOURCE.litcoffee >> doc/annotated-source.md
done
# Detect if pandoc is present and working
if pandoc --version &>/dev/null
  then
    echo "Compiling annotated source..."
    python scripts/add-coffeescript.py <doc/annotated-source.md | \
    pandoc --from markdown --to html5 --standalone --toc --smart -N \
           -o doc/annotated-source.html -
fi

