#!/bin/bash
echo '' > src/screens.js
echo '' > doc/annotated-source.md
SOURCES=""
SOURCES+=" clock socket data turnover keyboard day-sched display-select"
SOURCES+=" managers/container managers/override managers/clock"
SOURCES+=" managers/kill-origin managers/day-sched"
SOURCES+=" debug"
for SOURCE in $SOURCES
do
    echo "Compiling $SOURCE..."
    coffee --print src/coffee/$SOURCE.litcoffee >> src/screens.js
    cat src/coffee/$SOURCE.litcoffee >> doc/annotated-source.md
done
if [ -n "$(which pandoc)" ]
  then
    echo "Compiling annotated source..."
    python scripts/add-coffeescript.py <doc/annotated-source.md | \
    pandoc --from markdown --to html5 --standalone --toc --smart \
           -o doc/annotated-source.html -
fi

