#!/bin/bash
rm -rf dep
rm -rf node_modules
virtualenv dep
source dep/bin/activate
easy_install twisted
easy_install txredisapi
easy_install autobahn
source scripts/install-js-deps
npm install coffee-script
./compile

